spring:
  datasource:
    url: jdbc:mysql://10.81.44.187:3306/md?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root

server:
  port: 8081

