app_id: wx23b95852ed031837
app_secret: b76a67cf5cb87001ebda7366942c420e

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/md?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: root
    password: 852456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/web/dist/
#Redis-info
redis_host: 127.0.0.1
redis_port: 6379
redis_db: 11