#sunjian
#app_id:
#app_secret:
#yangang.li
app_id:
app_secret:

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/md?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: root
    password: 852456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    min-idle: 5
  gp-datasource:
    url: jdbc:postgresql://:3432/warehouse
    username: rpt
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    min-idle: 5
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 11
    timeout: 10000
  cache:
    type: redis
    redis:
      time-to-live: 2h

cas:
  server:
    host: http://:8080/casservice
    login: http://:8080/casservice/login
    logout: http://:8080/casservice/logout?service=http://aba.aihuishou.com:8080
  client:
    host: http://127.0.0.1:8084