spring:
  datasource:
    url: jdbc:mysql://:3306/mobi_dashboard?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: mobi_dashboard
  redis:
    host:
    database: 14

server:
  port: 8080

cas:
  client:
     host: https://
  server:
    host: https:///casservice
    login: https:///casservice/login
    logout: https:///casservice/logout?service=https://abdashboard.aihuishou.com