app_id:
app_secret:
spring:
  datasource:
    url: jdbc:mysql://192.168.5.63:3306/md?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 192.168.5.63
    database: 13
    password: 123456

server:
  port: 8080

cas:
   client:
     host: http://10.25.169.133:8084
